# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GrLIJKahfyXajlGOsQXY6ZC4LaTXc3S
"""

GEMINI_API_KEY='AIzaSyDBRFbn9GOrjwYqJcdS4gcGRXVY6zsslwM'

!pip install google-genai

from google import genai

client=genai.Client(api_key=GEMINI_API_KEY)

print(f"lets find the avaliable models")
for m in client.models.list():
   if m.supported_actions and 'generateContent' in m.supported_actions:
    print(f'-{m.name}')

from google.genai import types
config=types.GenerateContentConfig(
    temperature=0.1
)

prompt=input('Your Prompt')
print(f'Asking:{prompt}')

response=client.models.generate_content(
    model='gemini-3-flash-preview',
    contents=prompt,
    config=config
)
print(f'Output: ')
print(response.text)

config=types.GenerateContentConfig(
    temperature=0.7,
    system_instruction="You are a grumpy pirates. Always speak like a pirate"
)

chat=client.chats.create(
    model='gemini-3-flash-preview',
    config=config
    )

print(f'Pirate Chatbot is going to start! Type quit to exit the  conversation')
while True:
  user_input=input("You: ")
  if user_input=='quit':
    break
  print('Pirates: ',end=" ")
  reponse= chat.send_message_stream(user_input)
  for chunk in reponse:
     print(chunk.text,end=" ",flush=True)

  print('\n')

from PIL import Image # pillow for image generation

Image.new('RGB',(200,200),color='red').save('sampled.jpg')

myImage=Image.open("sampled.jpg")

myImage

prompt=[
    "what is the primary color of the image",
    "create a joke about the image",
    myImage
]


print(f'Asking gemini to look at the image')
response=client.models.generate_content(
    model='gemini-3-flash-preview',
    contents=prompt
)

print(response.text)

