# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-GrLIJKahfyXajlGOsQXY6ZC4LaTXc3S
"""

GEMINI_API_KEY='AIzaSyDBRFbn9GOrjwYqJcdS4gcGRXVY6zsslwM'

!pip install google-genai

from google import genai

client=genai.Client(api_key=GEMINI_API_KEY)

print(f"lets find the avaliable models")
for m in client.models.list():
   if m.supported_actions and 'generateContent' in m.supported_actions:
    print(f'-{m.name}')

from google.genai import types
config=types.GenerateContentConfig(
    temperature=0.1
)

prompt=input('Your Prompt')
print(f'Asking:{prompt}')

response=client.models.generate_content(
    model='gemini-3-flash-preview',
    contents=prompt,
    config=config
)